apiVersion: v1
kind: Service
metadata:
  labels:
    app: encrypted-file-storage
    environment: Development
  name: encrypted-file-storage
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: encrypted-file-storage
  sessionAffinity: None
  type: ClusterIP
